services:
  mariadb:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: infxs_landing
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: infxs
      MARIADB_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
